@url_base = http://localhost:5003/api/usuario

### Cadastrar usuário
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "email" : "adm@gmail.com",
    "senha" : "123@teste"
}

### Login
POST {{url_base}}/login
Content-Type: application/json

{
  "email": "adm@gmail.com",
  "senha": "123@teste"
}

### Listar usuários
GET {{url_base}}/listar